### ISSUE TITLE
Maybe allow a slower cron job so the user can pay less for the usage?

### ISSUE THREAD

**Issue by ronaldwraithco** [FoxxMD/laravel-elasticbeanstalk-cron#16]
I am trying to lower the budget. It would be greatly appreciate to be able to set the cron time for the application.

**Comment by Jono20201** [comment]
Hi @ronaldwraithco, which usage charges are you worried about?

**Comment by FoxxMD** [comment]
A few options:

### Decrease instance size

Use a smaller instance size for your elasticbeanstalk environment. This will probably give you the most cost savings.

### Increase interval between Laravel schedule calls

Currently the artisan command `schedule:run` is invoked by the cron every minute. You can find this in `Console/System/SetupSchedulerCommand.php` [line 57](https://github.com/FoxxMD/laravel-elasticbeanstalk-cron/blob/master/src/Console/System/SetupSchedulerCommand.php#L57).

Change `* * * * *` to whatever you want the interval to be IE `*/3 * * * *` is every three minutes...

### Increase interval between leader checks

Similarly you can increase the interval (in minutes) between checks for ec2 leaders by setting the `interval` parameter in `elasticbeanstalkcron.php` config file. The default value is 5 so it checks every 5 minutes.
___

The reasons I can think of that cron stuff would be incurring any significant costs for you:

* If your application is *huge* and requires CPU bursts that count against usage credits every time an artisan command is invoked. In this case alongside decreasing intervals you should consider refactoring your application.
* You are using spot instances. Decreasing intervals or setting it to specific times could help here but this is more of an infrastructure problem (when you are spinning up instances)
* **Most likely you are using an ec2 instance size that is larger than you need** in which case this package isn't the problem since usage costs are constant.

___

As far as modifying the cron schedule -- both commands already have code in place for accessing the `elasticbeanstalkcron.php` config file so modifying them to accept a cron schedule string, or anything with a bit more flexibility, should be easy! Please make a PR if you do make changes.

**Comment by goldnetonline** [comment]
Hi there, How do I stop a cron I don't need anymore.

Great work.

Thanks

**Comment by FoxxMD** [comment]
@goldnetonline Remove `USE_CRON` from your EB environment variables or set it to `false` to stop all leader selection.
